# docker-compose.production.yml
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: myapp-production
    ports:
      - "8082:3000"
    environment:
      - NODE_ENV=production
