# docker-compose.staging.yml
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: myapp-staging
    ports:
      - "8081:3000"
    environment:
      - NODE_ENV=staging
